# 
server:
  port: 443
  ssl:
    key-store: classpath:www.candata.cn.jks
    key-password: d6036g4321av1y9
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# Redis
spring:
  redis:
    host: localhost
#  MySQL
  datasource:
    url: jdbc:mysql://120.0.0.1:3306/any_db?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ci123456
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10

# Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
